[tools]
"aqua:suzuki-shunsuke/pinact" = "latest"
go = "latest"
"go:github.com/k1LoW/deck/cmd/deck" = "latest"
node = "22"
claude-code = "latest"
python = "latest"
uv = "latest"
watchexec = "latest"
"ubi:gitlab-org/cli" = { version = "latest", exe = "glab", provider = "gitlab" }
pnpm = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"npm:@playwright/cli" = "latest"
sentry = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

