[tools]
"aqua:suzuki-shunsuke/pinact" = "latest"
go = "latest"
"go:github.com/k1LoW/deck/cmd/deck" = "latest"
node = "24"
python = "latest"
uv = "latest"
watchexec = "latest"
"ubi:gitlab-org/cli" = { version = "latest", exe = "glab", provider = "gitlab" }
pnpm = "latest"
"npm:@playwright/cli" = "latest"
sentry = "latest"
claude = "latest"
"npm:cf" = "1.0.0-beta.12"
terraform = "latest"
"npm:difit" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

